using CalculosTrabalhistasTributarios.Domain.Financeiro;

namespace CalculosTrabalhistasTributarios.Application.DTOs;

public sealed record SimularEmprestimoPessoalRequest(EntradaEmprestimoPessoal Emprestimo);
