using CalculosTrabalhistasTributarios.Domain.Trabalhista;

namespace CalculosTrabalhistasTributarios.Application.DTOs;

public sealed record SimularReajusteRetroativoRequest(IReadOnlyList<ParcelaReajusteRetroativo> Parcelas);
